from setuptools import setup

setup(name='simplepy',
      version='0.1',
      description='Simple-pie!!!',
      url='http://github.com/pipeti/simplepy',
      author='Flying Circus',
      author_email='flyingcircus@example.com',
      license='MIT',
      packages=['simplepy'],
      install_requires=[
            'Flask==0.12.1',
            'Jinja2==2.8.1',
            'MarkupSafe==1.0',
            'Werkzeug==0.11.11',
            'click==6.6',
            'decorator==4.0.10',
            'functools32==3.2.3_2',
            'itsdangerous==0.24',
            'jsonpatch==1.15',
            'jsonpath-rw==1.4.0',
            'jsonpointer==1.10',
            'jsonschema==2.6.0',
            'kafka-python==1.3.3',
            'meld3==1.0.2',
            'ply==3.9',
            'requests==2.11.1',
            'six==1.10.0',
            'supervisor==3.2.3',
            'psycopg2==2.7.3.2',
            'gunicorn==19.7.1'
      ],
      zip_safe=False)
